### ISSUE TITLE
Black bar on top

### ISSUE THREAD

**Issue by tthanh** [wilfm/GnomeExtensionMaximusTwo#18] opened 2015-01-25 21:04 UTC
When i turn off one extension, it appear. I need switch tab to other windows, and switch back, black bar disappear.
I'm using Fedora 21, gnome 3.14.2
![screenshot from 2015-01-26 04 02 32](https://cloud.githubusercontent.com/assets/8962973/5893278/3e17c166-a510-11e4-9ae0-f848d7a84ed3.png)

**Comment by MingcongBai** [comment] 2015-02-10 15:59
Same thing has happened to Firefox, except that I can see the top panel. Firefox still has its window decoration taking place, but it's black.

**Comment by LeOSW42** [comment] 2015-02-11 09:13
Same problem here, even when all other extensions are disabled.

**Comment by elmeunick9** [comment] 2015-02-20 21:22
Same here

**Comment by DoctorJellyface** [comment] 2015-02-21 18:31
Same here, happens when I open a maximised window. Extremely annoying.

**Comment by wilfm** [comment] 2015-03-04 17:20
Same issue as in #12

**Comment by seveneves** [comment] 2015-03-10 17:10
Same issue on OpenSuse 3.12 and Gnome 3.14.2. The black bar appears after Gnome locks the desktop after inactivity. The bar disappears after minimizing and maximizing a window. All widows are effected.

**Comment by tekstryder** [comment] 2015-03-28 16:35
Confirmed on Arch Linux, Gnome 3.14.x. Seeing the additional black bar on top of various application windows. Also exhibits this behavior for existing windows on resume from suspend to ram.

**Comment by nommer** [comment] 2015-04-28 15:15
Still occurs in Arch Gnome 3.16.1, **but** disappears when I minimize the offending maximized window and re-maximize it (i.e., whenever I see the black bar, press Super+Down then Super+Up). 

So the solution is clearly to somehow embed that workaround in the extension. :smile:

**Comment by wilfm** [comment] 2015-08-05 13:54
Dupe of #12 - all should be fixed for now.

**Closed by wilfm** 2015-08-05 13:54 UTC
