### ISSUE TITLE
This extension crashes very often, several times per day, forcing me to restart gnome-shell

### ISSUE THREAD

**Issue by DigitalGrinch** [wilfm/GnomeExtensionMaximusTwo#38] opened 2015-10-03 17:03 UTC
Ubuntu-Gnome 15.04
gnome-shell 3.14.4

This extension crashes, causing the giant ugly title bars in gnome to take over. When I look at the extensions list in Tweak Tool, there is an Exclamation next to Maximus Two

I have to restart gnome shell, Alt+F2, then 'r' then 'Enter' in order to restore normal functionality

Can anything be done to fix this?

Also, when I switch focus from a Maximus Two maximized window, to a different window, and return to a maximized window, the window is never showing the full window. I have to 'Unmaximize' then 'Maximize' again to get it to display normally. This is more an inconvenience and is not as annoying as the extension crashing all the time. If this offers some insight as to why the extension keeps crashing, great.

**Comment by wilfm** [comment] 2015-10-04 12:32
What theme are you using, and do any errors appear in Looking Glass? (Press <kbd>Alt</kbd>+<kbd>F2</kbd>, enter `lg`, press Enter, and then select 'Extensions' > 'Maximus Two' > 'Show Errors'). Also which version of the extension are you using (you can see this in `~/.local/share/gnome-shell/extensions/maximus-two@wilfinitlike.gmail.com/metadata.json`)

**Comment by wilfm** [comment] 2015-11-07 22:04
Duplicate of #37 - anyway...

Just noticed a problem a problem occurred whilst uploading for 3.14 :/

Does the version from https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/4 work?

**Closed as completed by wilfm** 2015-11-07 22:04 UTC
Labels: duplicate
