### ISSUE TITLE
The plug-in doesn't work right away

### ISSUE THREAD

**Issue by thoys1** [wilfm/GnomeExtensionMaximusTwo#20] opened 2015-03-04 18:20 UTC
When I start a programm full-sized, there is another black space below the normal black bar. When I turn it into an window and maximise it again, than the black space disapears and everything like it should be. 

I use Debian 8 Jessie, with gnome 3.14

**Comment by najamelan** [comment] 2015-03-20 20:46
I had the same problem, and right now I have version 3.14.2-3+b1 of gnome-shell on debian jessie and I can't even get the extension to install anymore.

**Comment by wilfm** [comment] 2015-03-20 21:51
Probably a Dupe of #12 extensions would still install, you may need to close window and/or restart the shell (alt + f2 + r + enter)

Sry about the close issue thing, the button is in a stupid pace on three mobile interface...

**Comment by najamelan** [comment] 2015-03-21 01:00
yes, it looks like a duplicate.

about the installation, indeed when restarting gnome-shell the extension seemed to work, but my keyboard didn't anymore. When I wanted to use the menu on the panel to do switch user, the mouse clicks seemed to go through to the window underneath the menu, but the menu didn't respond to them. Ctrl-Alt-Backspace worked, and when I logged back in, the extensions was no longer enabled. The reason before when I tried reinstalling was also because gnome crached and after that it showed "error loading the extension".  Searching journalctl does not give any results on "maximus".

**Comment by wilfm** [comment] 2015-03-21 19:27
That sounds bad... does that happen when you restart the shell generally or just after installing the extension?

A similar problem with installation is mentioned here: https://github.com/wilfm/GnomeExtensionMaximusTwo/issues/16#issuecomment-77163868 . Make sure `xwininfo` and `xprop` are installed or it won't work. I probably need to add a thing that detects if that stuff is installed etc and does an alert...

**Comment by najamelan** [comment] 2015-03-22 19:49
It only happens after installing the extension. There is nothing being logged when installing. I have xprop and xwininfo. I tested a few more times to see the behavior is consistent.

**Comment by pezz** [comment] 2015-04-28 04:34
I can reliably reproduce by locking my desktop (e.g. Ctrl-Alt-L), then unlocking with my password.

I normally have gnome-terminal, Firefox and Hexchat maximised on 3 different virtual desktops. Firefox seems to restore fine, but gnome-terminal and hexchat have the extra bar between the top panel and the top of the application until I Meta+Mouse drag them.

**Comment by wilfm** [comment] 2015-08-05 13:52
May be fixed with https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/4 - I eventually got around to looking at the old version and it was positively ancient (still surprised it vaguely worked up to 3.16 at all), so the new version should work better

**Comment by wilfm** [comment] 2015-10-04 12:40
Closing as I think this should be fixed in the newer versions - please comment if you don't think it is.

**Closed by wilfm** 2015-10-04 12:40 UTC
