### ISSUE TITLE
I can't install this extension on my gnome 3.14.4

### ISSUE THREAD

**Issue by carlosotgz** [wilfm/GnomeExtensionMaximusTwo#36] opened 2015-10-02 23:50 UTC
Hello. I used to frequently reinstall this extension because sometimes I had some problems with it. Specifically, it reported an "error" on my Firefox browser so I found that method to be useful to get it working again without a GNOME reload. However, today I couldn't reinstall the extension again. Don't know if it was upgraded and now it is not compatible with my GNOME or distribution, I don't know. 
I was trying to find some kind of release history to manually download an older version but every attempt failed. 
I'm running Debian Jessie and my GNOME version is 3.14.4. I can provide any other information is needed. Thank oyou you so much in advance.

**Comment by wilfm** [comment] 2015-10-04 12:34
What theme are you using, and do any errors appear in Looking Glass? (Press <kbd>Alt</kbd>+<kbd>F2</kbd>, enter `lg`, press Enter, and then select 'Extensions' > 'Maximus Two' > 'Show Errors'). Also which version of the extension are you using (you can see this in `~/.local/share/gnome-shell/extensions/maximus-two@wilfinitlike.gmail.com/metadata.json`)

**Comment by carlosotgz** [comment] 2015-10-04 16:47
Hello again. I can check it by tomorrow (my PC is at work). However I guess I will have no version installed right now because every time I had any kind of problem with the extension, my solution was to simply remove and install it back again (it was faster than reloading GNOME). Unfortunately, this time I wasn't able to reinstall it again... I'm fact, then I set the "yes" option in the browser in the extension website, it never asks me for confirmation before install. It seems like it does nothing... Any idea? I will check for log tomorrow and I will share it with you. Thank you so much for your help. This is the most useful extension I have ever met.

**Comment by wilfm** [comment] 2015-11-07 22:03
Duplicate of #37 - anyway...

Just noticed a problem  a problem occurred whilst uploading for 3.14 :/

Does the version from https://github.com/wilfm/GnomeExtensionMaximusTwo/releases/tag/4 work?

**Closed as completed by wilfm** 2015-11-07 22:03 UTC
Labels: duplicate
